"""The preset catalogue, mirrored from the TypeScript source.

Generated by `scripts/sync_presets.py` — do not edit by hand.
`tests/test_data.py` fails if any preset here has no function in
`buildbox.data`.
"""

from __future__ import annotations

#: (category, preset name), in catalogue order.
PRESETS: list[tuple[str, str]] = [
    ('General', 'Kill Switch'),
    ('General', 'Script Runner'),
    ('General', 'Health Check'),
    ('General', 'CLI Terminal'),
    ('General', 'Data Logger'),
    ('General', 'Tailscale Peer'),
    ('General', 'AI API'),
    ('General', 'Generic Control'),
    ('General', 'Homing'),
    ('ROS2', 'ROS2 Topic Subscriber'),
    ('ROS2', 'ROS2 Topic Publisher'),
    ('ROS2', 'ROS2 Service Client'),
    ('ROS2', 'ROS2 Action Client'),
    ('ROS2', 'ROS2 Node Monitor'),
    ('ROS2', 'ROS2 Topic Monitor'),
    ('ROS2', 'ROS2 Parameter Server'),
    ('ROS2', 'ROS2 TF Monitor'),
    ('ROS2', 'ROS2 Bag Recorder'),
    ('ROS2', 'ROS2 Bag Player'),
    ('ROS2', 'ROS2 Diagnostics'),
    ('ROS2', 'ROS2 Image Stream'),
    ('ROS2', 'ROS2 Pointcloud Viewer'),
    ('ROS2', 'ROS2 Laser Scan'),
    ('ROS2', 'ROS2 Odometry'),
    ('ROS2', 'ROS2 Velocity Controller'),
    ('ROS2', 'ROS2 Joint State'),
    ('ROS2', 'ROS2 Map Viewer'),
    ('ROS2', 'ROS2 Goal Sender'),
    ('ROS2', 'ROS2 Lifecycle Manager'),
    ('IoT', 'MQTT Subscriber'),
    ('IoT', 'MQTT Publisher'),
    ('IoT', 'HTTP Poller'),
    ('IoT', 'Webhook Receiver'),
    ('IoT', 'Serial Monitor'),
    ('IoT', 'GPIO Controller'),
    ('IoT', 'I²C / SPI Sensor'),
    ('IoT', 'Modbus RTU/TCP'),
    ('IoT', 'OPC-UA Client'),
    ('IoT', 'CAN Bus Monitor'),
    ('IoT', 'Zigbee/Z-Wave Device'),
    ('IoT', 'BLE Scanner'),
    ('IoT', 'GPS / GNSS'),
    ('IoT', 'IMU'),
    ('IoT', 'Temperature / Humidity'),
    ('IoT', 'Power Monitor'),
    ('IoT', 'Camera Capture'),
    ('IoT', 'Relay Controller'),
    ('IoT', 'PID Controller'),
    ('IoT', 'Docker Monitor'),
    ('IoT', 'Systemd Service'),
    ('Analytical', 'Live Plotter'),
    ('Analytical', 'Gauge'),
    ('Analytical', 'Stat Tile'),
    ('Analytical', 'Histogram'),
    ('Analytical', 'Scatter Plot'),
    ('Analytical', 'Heatmap'),
    ('Analytical', 'Correlation Matrix'),
    ('Analytical', 'FFT Spectrum'),
    ('Analytical', 'Anomaly Detector'),
    ('Analytical', 'Rolling Statistics'),
    ('Analytical', 'Regression'),
    ('Analytical', 'Event Counter'),
    ('Analytical', 'Rate Meter'),
    ('Analytical', 'Latency Monitor'),
    ('Analytical', 'Threshold Alarm'),
    ('Analytical', 'Data Table'),
    ('Analytical', 'Comparison View'),
    ('Analytical', 'Report Generator'),
]

#: Just the names, in catalogue order.
PRESET_NAMES: list[str] = [name for _category, name in PRESETS]

#: Names grouped by category.
BY_CATEGORY: dict[str, list[str]] = {}
for _category, _name in PRESETS:
    BY_CATEGORY.setdefault(_category, []).append(_name)
