"""Regenerate the preset lists the language bindings mirror.

The catalogue lives once, in `packages/shared/src/catalog.ts`. The Python and C++
packages need to know the same names so their coverage tests can prove that every
preset has a function that feeds it, and neither can import TypeScript — so the
list is generated here rather than hand-copied, and this script is the only thing
that writes it.

    python scripts/sync_presets.py

Run it after adding a preset. The test suites fail if the generated lists drift,
which is the point: a new preset with no builder should be impossible to merge
quietly.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: Where the catalogue lives.
#:
#: This script is the only thing that writes the generated preset lists, and it
#: reads the catalogue from the product repository — which is *not* this one when
#: the libraries are checked out on their own. Set `BUILDBOX_CATALOGUE` to point
#: at it, or run this from a checkout that has both.
CATALOGUE = Path(
    os.environ.get(
        "BUILDBOX_CATALOGUE",
        ROOT / "packages" / "shared" / "src" / "catalog.ts",
    )
)

PYTHON_OUT = ROOT / "python" / "buildbox" / "presets.py"
CPP_OUT = ROOT / "cpp" / "include" / "buildbox" / "presets.hpp"

#: The TypeScript constant holding each category, and the category's name.
CATEGORIES = (
    ("GENERAL", "General"),
    ("ROS2", "ROS2"),
    ("IOT", "IoT"),
    ("ANALYTICAL", "Analytical"),
)


def read_catalogue() -> list[tuple[str, str]]:
    """(category, preset name) for every preset, in catalogue order."""
    if not CATALOGUE.exists():
        raise SystemExit(
            f"No catalogue at {CATALOGUE}.\n"
            "This script reads the preset catalogue out of the product repository.\n"
            "Point BUILDBOX_CATALOGUE at its packages/shared/src/catalog.ts."
        )
    source = CATALOGUE.read_text(encoding="utf-8")
    rows: list[tuple[str, str]] = []
    for constant, category in CATEGORIES:
        pattern = rf"const {constant}: Array<\[string, string\]> = \[(.*?)\n\];"
        match = re.search(pattern, source, re.S)
        if not match:
            raise SystemExit(f"Could not find the {constant} list in {CATALOGUE}.")
        for name in re.findall(r"^\s*\['([^']+)',", match.group(1), re.M):
            rows.append((category, name))
    if not rows:
        raise SystemExit(f"No presets parsed out of {CATALOGUE}.")
    return rows


def write_python(rows: list[tuple[str, str]]) -> None:
    lines = [
        '"""The preset catalogue, mirrored from the TypeScript source.',
        "",
        "Generated by `scripts/sync_presets.py` — do not edit by hand.",
        "`tests/test_data.py` fails if any preset here has no function in",
        "`buildbox.data`.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "#: (category, preset name), in catalogue order.",
        "PRESETS: list[tuple[str, str]] = [",
    ]
    lines += [f"    ({category!r}, {name!r})," for category, name in rows]
    lines += [
        "]",
        "",
        "#: Just the names, in catalogue order.",
        "PRESET_NAMES: list[str] = [name for _category, name in PRESETS]",
        "",
        "#: Names grouped by category.",
        "BY_CATEGORY: dict[str, list[str]] = {}",
        "for _category, _name in PRESETS:",
        "    BY_CATEGORY.setdefault(_category, []).append(_name)",
        "",
    ]
    PYTHON_OUT.parent.mkdir(parents=True, exist_ok=True)
    PYTHON_OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_cpp(rows: list[tuple[str, str]]) -> None:
    lines = [
        "// The preset catalogue, mirrored from the TypeScript source.",
        "//",
        "// Generated by `scripts/sync_presets.py` — do not edit by hand.",
        "// The tests fail if any preset here has no function in `buildbox/data.hpp`.",
        "",
        "#pragma once",
        "",
        "#include <string>",
        "#include <vector>",
        "",
        "namespace buildbox {",
        "",
        "/// One catalogue entry: its category and its name.",
        "struct Preset {",
        "  std::string category;",
        "  std::string name;",
        "};",
        "",
        "/// Every preset, in catalogue order.",
        "inline const std::vector<Preset>& presets() {",
        "  static const std::vector<Preset> all = {",
    ]
    lines += [
        f"      {{{c_string(category)}, {c_string(name)}}}," for category, name in rows
    ]
    lines += [
        "  };",
        "  return all;",
        "}",
        "",
        "}  // namespace buildbox",
        "",
    ]
    CPP_OUT.parent.mkdir(parents=True, exist_ok=True)
    CPP_OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    rows = read_catalogue()
    write_python(rows)
    write_cpp(rows)
    counts: dict[str, int] = {}
    for category, _name in rows:
        counts[category] = counts.get(category, 0) + 1
    summary = ", ".join(f"{category} {count}" for category, count in counts.items())
    print(f"wrote {len(rows)} presets ({summary})")
    print(f"  {PYTHON_OUT.relative_to(ROOT)}")
    print(f"  {CPP_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
